sudo: required
services:
  - docker

before_install:
  - docker build -t brianrienecker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brianrienecker/react-test npm test 

after_success:
  - docker build -t brianrienecker/multi-client ./client
  - docker build -t brianrienecker/multi-nginx ./nginx
  - docker build -t brianrienecker/multi-server ./server
  - docker build -t brianrienecker/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push brianrienecker/multi-client
  - docker push brianrienecker/multi-nginx
  - docker push brianrienecker/multi-server
  - docker push brianrienecker/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-940768505932
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  